version: '3.8'
services:
  web_panel:
    build:
      context: ./services/web_panel
    ports:
      - "5001:5001"
    volumes:
      - ./services/web_panel:/app
      - ./telemeet.db:/app/telemeet.db
    shm_size: '2gb'
