version: '3.8'
services:
  web_panel:
    build:
      context: ./services/web_panel
    ports:
      - "5001:5001"
    volumes:
      - ./services/web_panel:/app
    environment:
      - DATABASE_URL=sqlite:////app/telemeet.db
  telegram_bot:
    build:
      context: ./services/telegram_bot
    ports:
      - "5002:5002"
    volumes:
      - ./services/telegram_bot:/app
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - web_panel
  selenium_automation:
    build:
      context: ./services/selenium_automation
    ports:
      - "5003:5003"
    volumes:
      - ./services/selenium_automation:/app
    shm_size: '2gb'
    depends_on:
      - web_panel
